import Config

config :framework, :files,
  uploads_dir: Path.expand("../priv/uploads", __DIR__),
  host: [scheme: "http", host: "localhost", port: 4000],
  server_ip: "127.0.0.1",
  hostname: "localhost",
  transport_opts: []

config :phoenix_copy,
  css: [
    source: Path.expand("../assets/static/css/", __DIR__),
    destination: Path.expand("../priv/static/assets/", __DIR__)
  ],
  images: [
    source: Path.expand("../assets/static/images/", __DIR__),
    destination: Path.expand("../priv/static/images/", __DIR__)
  ],
  js: [
    source: Path.expand("../assets/static/js/", __DIR__),
    destination: Path.expand("../priv/static/assets/", __DIR__)
  ],
  fonts: [
    source: Path.expand("../assets/static/fonts/", __DIR__),
    destination: Path.expand("../priv/static/fonts/", __DIR__)
  ]

# Configure your database
config :framework, Framework.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "framework_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :bun,
  version: "1.1.42",
  serviceworker: [
    args: ~w(js/serviceworker.js --outdir=../priv/static/assets),
    cd: Path.expand("../assets", __DIR__),
    env: %{"ENV_VAR" => "value"}
  ]

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :framework, FrameworkWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "tWtsjqdpRceYk4iSAM5NMjAEvFXQdldhf+2njEp6+0iAwXzJ5O+xpErYOBcrl3yr",
  watchers: [
    asset_copy_css: {Phoenix.Copy, :watch, [:css]},
    asset_copy_images: {Phoenix.Copy, :watch, [:images]},
    asset_copy_js: {Phoenix.Copy, :watch, [:js]},
    asset_copy_fonts: {Phoenix.Copy, :watch, [:fonts]},
    esbuild: {Esbuild, :install_and_run, [:framework, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:framework, ~w(--watch)]},
    serviceworker: {Bun, :install_and_run, [:serviceworker, ~w(--sourcemap=inline --watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :framework, FrameworkWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/framework_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :framework, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

config :framework, FrameworkWeb, secret_key: "abc"
